//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OctopathTraveler.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OctopathTraveler.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Achievement Progress: (Following data) 的本地化字符串。
        /// </summary>
        public static string BasicAchievementProgress {
            get {
                return ResourceManager.GetString("BasicAchievementProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 BattleCount 的本地化字符串。
        /// </summary>
        public static string BasicBattleCount {
            get {
                return ResourceManager.GetString("BasicBattleCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 EscapeCount 的本地化字符串。
        /// </summary>
        public static string BasicEscapeCount {
            get {
                return ResourceManager.GetString("BasicEscapeCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hero 的本地化字符串。
        /// </summary>
        public static string BasicHero {
            get {
                return ResourceManager.GetString("BasicHero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 HiddenPointCount 的本地化字符串。
        /// </summary>
        public static string BasicHiddenPointCount {
            get {
                return ResourceManager.GetString("BasicHiddenPointCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Money 的本地化字符串。
        /// </summary>
        public static string BasicMoney {
            get {
                return ResourceManager.GetString("BasicMoney", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PlayTime 的本地化字符串。
        /// </summary>
        public static string BasicPlayTime {
            get {
                return ResourceManager.GetString("BasicPlayTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SaveDate 的本地化字符串。
        /// </summary>
        public static string BasicSaveDate {
            get {
                return ResourceManager.GetString("BasicSaveDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 TreasureCount 的本地化字符串。
        /// </summary>
        public static string BasicTreasureCount {
            get {
                return ResourceManager.GetString("BasicTreasureCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] InfoExcel {
            get {
                object obj = ResourceManager.GetObject("InfoExcel", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 Accessory1 的本地化字符串。
        /// </summary>
        public static string ItemAccessory1 {
            get {
                return ResourceManager.GetString("ItemAccessory1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Accessory2 的本地化字符串。
        /// </summary>
        public static string ItemAccessory2 {
            get {
                return ResourceManager.GetString("ItemAccessory2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Axe 的本地化字符串。
        /// </summary>
        public static string ItemAxe {
            get {
                return ResourceManager.GetString("ItemAxe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Body 的本地化字符串。
        /// </summary>
        public static string ItemBody {
            get {
                return ResourceManager.GetString("ItemBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Bow 的本地化字符串。
        /// </summary>
        public static string ItemBow {
            get {
                return ResourceManager.GetString("ItemBow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cancel 的本地化字符串。
        /// </summary>
        public static string ItemChoiceCancel {
            get {
                return ResourceManager.GetString("ItemChoiceCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Filter 的本地化字符串。
        /// </summary>
        public static string ItemChoiceFilter {
            get {
                return ResourceManager.GetString("ItemChoiceFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OK 的本地化字符串。
        /// </summary>
        public static string ItemChoiceOK {
            get {
                return ResourceManager.GetString("ItemChoiceOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Item Selection 的本地化字符串。
        /// </summary>
        public static string ItemChoiceTitle {
            get {
                return ResourceManager.GetString("ItemChoiceTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Dagger 的本地化字符串。
        /// </summary>
        public static string ItemDagger {
            get {
                return ResourceManager.GetString("ItemDagger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Dark 的本地化字符串。
        /// </summary>
        public static string ItemDark {
            get {
                return ResourceManager.GetString("ItemDark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Fire 的本地化字符串。
        /// </summary>
        public static string ItemFire {
            get {
                return ResourceManager.GetString("ItemFire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Head 的本地化字符串。
        /// </summary>
        public static string ItemHead {
            get {
                return ResourceManager.GetString("ItemHead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ice 的本地化字符串。
        /// </summary>
        public static string ItemIce {
            get {
                return ResourceManager.GetString("ItemIce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Lance 的本地化字符串。
        /// </summary>
        public static string ItemLance {
            get {
                return ResourceManager.GetString("ItemLance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Light 的本地化字符串。
        /// </summary>
        public static string ItemLight {
            get {
                return ResourceManager.GetString("ItemLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Rod 的本地化字符串。
        /// </summary>
        public static string ItemRod {
            get {
                return ResourceManager.GetString("ItemRod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Shield 的本地化字符串。
        /// </summary>
        public static string ItemShield {
            get {
                return ResourceManager.GetString("ItemShield", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sword 的本地化字符串。
        /// </summary>
        public static string ItemSword {
            get {
                return ResourceManager.GetString("ItemSword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Thunder 的本地化字符串。
        /// </summary>
        public static string ItemThunder {
            get {
                return ResourceManager.GetString("ItemThunder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Wind 的本地化字符串。
        /// </summary>
        public static string ItemWind {
            get {
                return ResourceManager.GetString("ItemWind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OCTOPATH TRAVELER SaveDataEditor 的本地化字符串。
        /// </summary>
        public static string MainWindowTitle {
            get {
                return ResourceManager.GetString("MainWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save Fail 的本地化字符串。
        /// </summary>
        public static string MeaageSaveFail {
            get {
                return ResourceManager.GetString("MeaageSaveFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 (_A)bout 的本地化字符串。
        /// </summary>
        public static string MenuAbout {
            get {
                return ResourceManager.GetString("MenuAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 (_E)xit 的本地化字符串。
        /// </summary>
        public static string MenuExit {
            get {
                return ResourceManager.GetString("MenuExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 (_E)xport Embedded Info Excel... 的本地化字符串。
        /// </summary>
        public static string MenuExportInfoExcel {
            get {
                return ResourceManager.GetString("MenuExportInfoExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 (_F)ile 的本地化字符串。
        /// </summary>
        public static string MenuFile {
            get {
                return ResourceManager.GetString("MenuFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 (_O)pen 的本地化字符串。
        /// </summary>
        public static string MenuFileOpen {
            get {
                return ResourceManager.GetString("MenuFileOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 (_S)ave 的本地化字符串。
        /// </summary>
        public static string MenuFileSave {
            get {
                return ResourceManager.GetString("MenuFileSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save (_A)s... 的本地化字符串。
        /// </summary>
        public static string MenuFileSaveAs {
            get {
                return ResourceManager.GetString("MenuFileSaveAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save As (_J)son... 的本地化字符串。
        /// </summary>
        public static string MenuFileSaveAsJson {
            get {
                return ResourceManager.GetString("MenuFileSaveAsJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Load Success 的本地化字符串。
        /// </summary>
        public static string MessageLoadSuccess {
            get {
                return ResourceManager.GetString("MessageLoadSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save Success 的本地化字符串。
        /// </summary>
        public static string MessageSaveSuccess {
            get {
                return ResourceManager.GetString("MessageSaveSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Country 的本地化字符串。
        /// </summary>
        public static string QuestsCountry {
            get {
                return ResourceManager.GetString("QuestsCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Basic 的本地化字符串。
        /// </summary>
        public static string TabItemBasic {
            get {
                return ResourceManager.GetString("TabItemBasic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Character 的本地化字符串。
        /// </summary>
        public static string TabItemCharacter {
            get {
                return ResourceManager.GetString("TabItemCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Items 的本地化字符串。
        /// </summary>
        public static string TabItemItems {
            get {
                return ResourceManager.GetString("TabItemItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Party 的本地化字符串。
        /// </summary>
        public static string TabItemParty {
            get {
                return ResourceManager.GetString("TabItemParty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Places 的本地化字符串。
        /// </summary>
        public static string TabItemPlaces {
            get {
                return ResourceManager.GetString("TabItemPlaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Some of the places on this page may be missing names, and some place IDs cannot be found, possibly because they were abandoned during game development and not removed. 的本地化字符串。
        /// </summary>
        public static string TabItemPlacesWarning {
            get {
                return ResourceManager.GetString("TabItemPlacesWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Quests 的本地化字符串。
        /// </summary>
        public static string TabItemQuests {
            get {
                return ResourceManager.GetString("TabItemQuests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 TameMonster 的本地化字符串。
        /// </summary>
        public static string TabItemTameMonster {
            get {
                return ResourceManager.GetString("TabItemTameMonster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The monsters selected in the drop down options on this page may not be valid tameable monsters, so please be careful when modifying tamed monsters to avoid damaging your archive. 的本地化字符串。
        /// </summary>
        public static string TabItemTameMonsterWarning {
            get {
                return ResourceManager.GetString("TabItemTameMonsterWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 TreasureStates 的本地化字符串。
        /// </summary>
        public static string TabItemTreasure {
            get {
                return ResourceManager.GetString("TabItemTreasure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Weakness 的本地化字符串。
        /// </summary>
        public static string TabItemWeak {
            get {
                return ResourceManager.GetString("TabItemWeak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Convert SaveData to Json 的本地化字符串。
        /// </summary>
        public static string ToolTipConvert {
            get {
                return ResourceManager.GetString("ToolTipConvert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open 的本地化字符串。
        /// </summary>
        public static string ToolTipOpen {
            get {
                return ResourceManager.GetString("ToolTipOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save 的本地化字符串。
        /// </summary>
        public static string ToolTipSave {
            get {
                return ResourceManager.GetString("ToolTipSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save As Json 的本地化字符串。
        /// </summary>
        public static string ToolTipSaveAsJson {
            get {
                return ResourceManager.GetString("ToolTipSaveAsJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Chest 的本地化字符串。
        /// </summary>
        public static string TreasureStatesChest {
            get {
                return ResourceManager.GetString("TreasureStatesChest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 HiddenItem 的本地化字符串。
        /// </summary>
        public static string TreasureStatesHiddenItem {
            get {
                return ResourceManager.GetString("TreasureStatesHiddenItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Summation 的本地化字符串。
        /// </summary>
        public static string TreasureStatesSummation {
            get {
                return ResourceManager.GetString("TreasureStatesSummation", resourceCulture);
            }
        }
    }
}
