//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OctopathTraveler.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OctopathTraveler.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Money 的本地化字符串。
        /// </summary>
        public static string BacisMoney {
            get {
                return ResourceManager.GetString("BacisMoney", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hero 的本地化字符串。
        /// </summary>
        public static string BasicHero {
            get {
                return ResourceManager.GetString("BasicHero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cancel 的本地化字符串。
        /// </summary>
        public static string ItemChoiceCancel {
            get {
                return ResourceManager.GetString("ItemChoiceCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Filter 的本地化字符串。
        /// </summary>
        public static string ItemChoiceFilter {
            get {
                return ResourceManager.GetString("ItemChoiceFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OK 的本地化字符串。
        /// </summary>
        public static string ItemChoiceOK {
            get {
                return ResourceManager.GetString("ItemChoiceOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Item Selection 的本地化字符串。
        /// </summary>
        public static string ItemChoiceTitle {
            get {
                return ResourceManager.GetString("ItemChoiceTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Accessory1 的本地化字符串。
        /// </summary>
        public static string ItemWeakAccessory1 {
            get {
                return ResourceManager.GetString("ItemWeakAccessory1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Accessory2 的本地化字符串。
        /// </summary>
        public static string ItemWeakAccessory2 {
            get {
                return ResourceManager.GetString("ItemWeakAccessory2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Axe 的本地化字符串。
        /// </summary>
        public static string ItemWeakAxe {
            get {
                return ResourceManager.GetString("ItemWeakAxe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Body 的本地化字符串。
        /// </summary>
        public static string ItemWeakBody {
            get {
                return ResourceManager.GetString("ItemWeakBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Bow 的本地化字符串。
        /// </summary>
        public static string ItemWeakBow {
            get {
                return ResourceManager.GetString("ItemWeakBow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Dagger 的本地化字符串。
        /// </summary>
        public static string ItemWeakDagger {
            get {
                return ResourceManager.GetString("ItemWeakDagger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Dark 的本地化字符串。
        /// </summary>
        public static string ItemWeakDark {
            get {
                return ResourceManager.GetString("ItemWeakDark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Fire 的本地化字符串。
        /// </summary>
        public static string ItemWeakFire {
            get {
                return ResourceManager.GetString("ItemWeakFire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Head 的本地化字符串。
        /// </summary>
        public static string ItemWeakHead {
            get {
                return ResourceManager.GetString("ItemWeakHead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ice 的本地化字符串。
        /// </summary>
        public static string ItemWeakIce {
            get {
                return ResourceManager.GetString("ItemWeakIce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Lance 的本地化字符串。
        /// </summary>
        public static string ItemWeakLance {
            get {
                return ResourceManager.GetString("ItemWeakLance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Light 的本地化字符串。
        /// </summary>
        public static string ItemWeakLight {
            get {
                return ResourceManager.GetString("ItemWeakLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Rod 的本地化字符串。
        /// </summary>
        public static string ItemWeakRod {
            get {
                return ResourceManager.GetString("ItemWeakRod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Shield 的本地化字符串。
        /// </summary>
        public static string ItemWeakShield {
            get {
                return ResourceManager.GetString("ItemWeakShield", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sword 的本地化字符串。
        /// </summary>
        public static string ItemWeakSword {
            get {
                return ResourceManager.GetString("ItemWeakSword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Thunder 的本地化字符串。
        /// </summary>
        public static string ItemWeakThunder {
            get {
                return ResourceManager.GetString("ItemWeakThunder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Wind 的本地化字符串。
        /// </summary>
        public static string ItemWeakWind {
            get {
                return ResourceManager.GetString("ItemWeakWind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OCTOPATH TRAVELER SaveDataEditor(Nintendo Switch) 的本地化字符串。
        /// </summary>
        public static string MainWindowTitle {
            get {
                return ResourceManager.GetString("MainWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save Fail 的本地化字符串。
        /// </summary>
        public static string MeaageSaveFail {
            get {
                return ResourceManager.GetString("MeaageSaveFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 (_A)bout 的本地化字符串。
        /// </summary>
        public static string MenuAbout {
            get {
                return ResourceManager.GetString("MenuAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 (_E)xit 的本地化字符串。
        /// </summary>
        public static string MenuExit {
            get {
                return ResourceManager.GetString("MenuExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 (_F)ile 的本地化字符串。
        /// </summary>
        public static string MenuFile {
            get {
                return ResourceManager.GetString("MenuFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 (_O)pen 的本地化字符串。
        /// </summary>
        public static string MenuFileOpen {
            get {
                return ResourceManager.GetString("MenuFileOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 (_S)ave 的本地化字符串。
        /// </summary>
        public static string MenuFileSave {
            get {
                return ResourceManager.GetString("MenuFileSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save(_A)s... 的本地化字符串。
        /// </summary>
        public static string MenuFileSaveAs {
            get {
                return ResourceManager.GetString("MenuFileSaveAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Load Success 的本地化字符串。
        /// </summary>
        public static string MessageLoadSuccess {
            get {
                return ResourceManager.GetString("MessageLoadSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save Success 的本地化字符串。
        /// </summary>
        public static string MessageSaveSuccess {
            get {
                return ResourceManager.GetString("MessageSaveSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Country 的本地化字符串。
        /// </summary>
        public static string QuestsCountry {
            get {
                return ResourceManager.GetString("QuestsCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Basic 的本地化字符串。
        /// </summary>
        public static string TabItemBasic {
            get {
                return ResourceManager.GetString("TabItemBasic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Character 的本地化字符串。
        /// </summary>
        public static string TabItemCharacter {
            get {
                return ResourceManager.GetString("TabItemCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Items 的本地化字符串。
        /// </summary>
        public static string TabItemItems {
            get {
                return ResourceManager.GetString("TabItemItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Party 的本地化字符串。
        /// </summary>
        public static string TabItemParty {
            get {
                return ResourceManager.GetString("TabItemParty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Places 的本地化字符串。
        /// </summary>
        public static string TabItemPlaces {
            get {
                return ResourceManager.GetString("TabItemPlaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Quests 的本地化字符串。
        /// </summary>
        public static string TabItemQuests {
            get {
                return ResourceManager.GetString("TabItemQuests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 TameMonster 的本地化字符串。
        /// </summary>
        public static string TabItemTameMonster {
            get {
                return ResourceManager.GetString("TabItemTameMonster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 TreasureStates 的本地化字符串。
        /// </summary>
        public static string TabItemTreasure {
            get {
                return ResourceManager.GetString("TabItemTreasure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Weak 的本地化字符串。
        /// </summary>
        public static string TabItemWeak {
            get {
                return ResourceManager.GetString("TabItemWeak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open 的本地化字符串。
        /// </summary>
        public static string ToolTipOpen {
            get {
                return ResourceManager.GetString("ToolTipOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save 的本地化字符串。
        /// </summary>
        public static string ToolTipSave {
            get {
                return ResourceManager.GetString("ToolTipSave", resourceCulture);
            }
        }
    }
}
